version: '3'

services:
  redis:
    image: bitnami/redis:6.0
#    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_PASSWORD=password
    networks:
      - redis-net
    # volumes:
    #   - redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
    # command: >

networks:
  redis-net:

# volumes:
#   redis-data:
