version: '3'

services:
  vault:
    image: "vault:1.1.3"
    ports:
      - "8200:8200"
    volumes:
      - "$HOME/Development/data/vault/file:/vault/file"
      - "$HOME/Development/data/vault/config:/vault/config"
    environment:
      - 'VAULT_LOCAL_CONFIG={"ui": true, "backend": {"file": {"path": "/vault/file"}}, "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": 1}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    command: "server"
    cap_add: 
      - IPC_LOCK
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"