version: '3'

services:
  # gw:
  #   image: nginx
  #   ports:
  #     - "8180:80"
  #   volumes: 
  #     - "./html:/usr/share/nginx/html"
  #     - "./nginx.conf:/etc/nginx/nginx.conf"
  #   links:
  #     - srs
  srs:
    image: ossrs/srs:v4.0.36
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
    volumes:
      - "./srs.conf:/usr/local/srs/conf/srs.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
    # command: >

# volumes:
#   srs-data:
