version: '3'

services:
  # metricbeat:
  #   image: docker.elastic.co/beats/metricbeat:7.2.0
  #   environment:
  #     - MYSQL_PASSWORD=password
  #   volumes:
  #     - ./metricbeat.mysql.yml:/usr/share/metricbeat/modules.d/mysql.yml
  #   command: >
  #     metricbeat -e -E setup.kibana.host=kibana:5601 -E output.elasticsearch.hosts=['elasticsearch:9200']
  #   links:
  #     - kibana
  #     - elasticsearch
  kibana:
    image: bitnami/kibana:7
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    ports:
      - 5601:5601
    volumes:
      - "$HOME/Development/data/kibana:/bitnami"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
    links:
      - elasticsearch
  elasticsearch:
    image: bitnami/elasticsearch:7
#    environment:
#      - ELASTICSEARCH_IS_DEDICATED_NODE=yes
#      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
#      - ES_JAVA_OPTS=-Xmx1g -Xms1g
#      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - "$HOME/Development/data/elasticsearch:/bitnami/elasticsearch/data"
      - "$PWD/elasticsearch.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
#  elasticsearch_ingest:
#      image: bitnami/elasticsearch:7
#      environment:
#        - ELASTICSEARCH_NODE_TYPE=ingest
#  #      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
#  #      - ES_JAVA_OPTS=-Xmx1g -Xms1g
#  #      - discovery.type=single-node
##      ports:
##        - 9200:9200
##        - 9300:9300
##      volumes:
##        - "$HOME/Development/data/elasticsearch:/bitnami/elasticsearch/data"
#      logging:
#        driver: "json-file"
#        options:
#          max-size: "1k"
#          max-file: "1"
#      ulimits:
#        nofile:
#          soft: 65536
#          hard: 65536
