version: '3'

services:
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:4.8"
    ports:
      - "20080:80"
    environment:
      - "PMA_HOST=host.docker.internal"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - "$HOME/Development/data/mysql:/var/lib/mysql"
  nexus:
    image: "sonatype/nexus3:3.13.0"
    ports:
      - "8081:8081"
    volumes:
      - "$HOME/Development/data/nexus-data:/nexus-data"
