version: '3'

services:
  gw:
    image: abiosoft/caddy
    environment: 
      - CADDYPATH=/etc/caddycerts
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./caddycerts:/etc/caddycerts