version: '3'

services:
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:5.0"
    ports:
      - "20080:80"
    environment:
      # - "PMA_ARBITRARY=1"
      - "PMA_HOSTS=host.docker.internal"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - "$HOME/Development/data/mysql:/var/lib/mysql"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
    # command: >
