version: '3'

services:
  jaegertracing:
    image: jaegertracing/all-in-one:1.19
    ports: 
      # - 5775:5775/udp # agent - accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
      - 6831:6831/udp # agent - accept jaeger.thrift over compact thrift protocol
      # - 6832:6832/udp # agent - accept jaeger.thrift over binary thrift protocol
      - 5778:5778 # agent - serve configs
      - 16686:16686 # query - serve frontend
      - 14268:14268 # collector - accept jaeger.thrift directly from clients
      - 9411:9411 # collector - Zipkin compatible endpoint (optional)
