version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - "./html:/usr/share/nginx/html:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "$HOME/Development/data/nginx:/var/log/nginx:rw"
    ports:
      - 8080:80
      - 8443:443
