version: '3'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://172.17.0.1:9200
    ports:
      - 5601:5601
    volumes:
      - "$PWD/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
