version: '3'

services:
  nexus:
    image: "sonatype/nexus3:3.13.0"
    ports:
      - "8081:8081"
    volumes:
      - "$HOME/Development/data/nexus-data:/nexus-data"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
