version: '3.1'

services:
  mongo-express:
    image: "mongo-express:0.54"
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
  mongo:
    image: "mongo:4.2-bionic"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "$HOME/Development/data/mongo:/data/db"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
    # command: >
