version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8.0-management-alpine
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq-net
    environment:
      - 'RABBITMQ_DEFAULT_USER=user'
      - 'RABBITMQ_DEFAULT_PASS=password'
    volumes:
      - rabbitmq-data:/var/lib/
      - rabbitmq-config:/etc/rabbitmq/
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
    # command: >

networks:
  rabbitmq-net:

volumes:
  rabbitmq-data:
  rabbitmq-config:
