version: '3'

services:
  phpmyadmin:
    image: "bitnami/phpmyadmin:5"
    ports:
      - "20080:8080"
    environment:
      - "DATABASE_HOST=host.docker.internal"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
  mysql:
    image: "bitnami/mysql:5.7"
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - "$HOME/Development/data/mysql:/bitnami/mysql/data"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
    # command: >
